version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directories:
      - "**/rootfs"
    schedule:
      interval: "weekly"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
    groups:
      docker:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "**/rootfs"
    schedule:
      interval: "weekly"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
    groups:
      go:
        update-types:
          - "patch"
